apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /api/account
        pathType: Prefix
        backend:
          service:
            name: account-service
            port: 
              number: 80
      - path: /api/authentication
        pathType: Prefix
        backend:
          service:
            name: authentication-service
            port:
              number: 80
      - path: /api/product
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 80
      - path: /api/management
        pathType: Prefix
        backend:
          service:
            name: management-service
            port:
              number: 80
      - path: /api/payment
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
